version: '3'

services:
  qmk_compiler:
    build: ../qmk_compiler
    environment:
      GRAPHITE_HOST: ec2-18-207-221-22.compute-1.amazonaws.com
      MINIO_ACCESS_KEY: minio_dev
      MINIO_SECRET_KEY: minio_dev_secret
      PYTHONUNBUFFERED: 1
      API_URL: http://log8415-API-elb-1744024168.us-east-1.elb.amazonaws.com:5001/
      LOG_LEVEL: DEBUG
      #QMK_GIT_URL: https://github.com/qmk/qmk_firmware.git
      #QMK_GIT_BRANCH: master
      REDIS_HOST: ec2-18-207-221-22.compute-1.amazonaws.com
      RELOAD: 1
      S3_HOST: http://ec2-18-207-221-22.compute-1.amazonaws.com:9000
    volumes:
    - ../qmk_compiler:/qmk_compiler