version: '3'

services:
  qmk_compiler:
    build: ../qmk_compiler
    environment:
      GRAPHITE_HOST: ec2-3-237-84-24.compute-1.amazonaws.com
      MINIO_ACCESS_KEY: minio_dev
      MINIO_SECRET_KEY: minio_dev_secret
      PYTHONUNBUFFERED: 1
      API_URL: http://ec2-52-23-211-143.compute-1.amazonaws.com:5001/
      LOG_LEVEL: DEBUG
      #QMK_GIT_URL: https://github.com/qmk/qmk_firmware.git
      #QMK_GIT_BRANCH: master
      REDIS_HOST: ec2-3-237-84-24.compute-1.amazonaws.com
      RELOAD: 1
      S3_HOST: http://ec2-3-237-84-24.compute-1.amazonaws.com:9000
    volumes:
    - ../qmk_compiler:/qmk_compiler