version: '3'

services:
  qmk_api:
    build: ../qmk_api
    ports:
      - "5001:5000"
    environment:
      PYTHONUNBUFFERED: 1
      API_URL: http://qmk_api:5001/
      #QMK_GIT_URL: https://github.com/qmk/qmk_firmware.git
      #QMK_GIT_BRANCH: master
      FLASK_GRAPHITE_HOST: qmk_metrics_aggregator
      REDIS_HOST: redis
      RELOAD: 1
      S3_HOST: http://minio:9000
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
      UPDATE_API: 'true'
    volumes:
    - ../qmk_api:/qmk_api
    - ../qmk_compiler:/qmk_compiler