version: '3'

services:
  qmk_api:
    build: ../qmk_api
    ports:
      - "5001:5000"
    environment:
      PYTHONUNBUFFERED: 1
      API_URL: http://log8415-API-elb-1484986348.us-east-1.elb.amazonaws.com/
      #QMK_GIT_URL: https://github.com/qmk/qmk_firmware.git
      #QMK_GIT_BRANCH: master
      FLASK_GRAPHITE_HOST: ec2-3-86-103-54.compute-1.amazonaws.com
      REDIS_HOST: ec2-3-86-103-54.compute-1.amazonaws.com
      RELOAD: 1
      S3_HOST: http://ec2-3-86-103-54.compute-1.amazonaws.com:9000
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
      UPDATE_API: 'true'
    volumes:
    - ../qmk_api:/qmk_api
    #- ../qmk_compiler:/qmk_compiler
  qmk_configurator:
    build: ../qmk_configurator
    ports:
      - "80:80"
    environment:
      QMK_API_URL: http://qmk_api:5001
